Feature/jwt
bodya4243/online-book-store pull request #10
Opened 2024-05-15 07:45 UTC by bodya4243

1) Add JWT

2024-05-15 10:29 UTC, vovasalyha requested changes
Looks good, but see a couple of comments.

2024-05-15 10:29 UTC, vovasalyha commented on pom.xml
> +			<version>0.11.2</version>
It's a good practice to extract versions to properties.

2024-05-15 10:29 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**","/swagger-ui/**")
Also, add `/v3/api-docs/**`

2024-05-15 10:29 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/dto/UserLoginRequestDto.java
> +        @Size(min = 8, max = 20)
20 chars for email seems too restrictive. I'm sure there are a lot of longer emails.

2024-05-15 10:29 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/security/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
```suggestion
            return false;
```

2024-05-15 10:29 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
This number can be a bit magic if you are not in the context and looking at it the first time.

2024-05-15 10:29 UTC, vovasalyha commented on src/main/resources/application.properties
> +jwt.secret=wefwqfdfwqfq4f3fq3af43453452ef34fewfewfe
It's better to get sensitive properties from system properties and not pushing it to git.

2024-05-15 16:23 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make string literal constants

2024-05-15 16:23 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(BEARER_PREFIX_LENGTH);
```suggestion
            return bearerToken.substring("Bearer ".length);
```

2024-05-15 16:23 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**","/swagger-ui/**")
I don`t see this changes

2024-05-15 16:23 UTC, andrii-hoienko requested changes
Nice, left some minor comments

2024-05-15 17:54 UTC, bodya4243 commented
/v3/api-docs/** is already in project.
![image](https://github.com/bodya4243/online-book-store/assets/105318502/b61818db-34df-412f-86c1-f68993d98fb8)

2024-05-16 08:22 UTC, karma-o approved these changes
GJ!

2024-05-16 08:22 UTC, karma-o commented on src/main/java/com/example/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring("Bearer ".length());
```suggestion
            return bearerToken.substring(BEARER_PREFIX.length());
```

2024-05-16 11:34 UTC, merged