feature/category
bodya4243/online-book-store pull request #11
Opened 2024-05-17 11:45 UTC by bodya4243

1) add category entity

2024-05-20 13:27 UTC, andrii-hoienko requested changes
Good job! Left some comments

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/controller/CategoryController.java
> +
```suggestion
```

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/dto/CategoryRequestDto.java
> +    private String description;
Please set max constraint to align with db constraints

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/mapper/BookMapper.java
> +
```suggestion
```

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany(fetch = FetchType.LAZY)
```

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/model/Book.java
> +    private Set<Category> categoryId = new HashSet<>();
Please exclude this from equals and hashCode

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +    List<Book> findAllByCategoryId_Id(Long categoryId);
Better to keep naming convention

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/BookServiceImpl.java
>          return bookMapper.toDto(bookRepository.save(book));
You should save and validate categories as well

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/insert-categories.yml
> +                  valueBoolean: false
```suggestion
                  valueBoolean: false
                  
```

2024-05-20 13:27 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/insert-books-categories.yml
> +                  value: 3
Please use valueComputed instead hardcoding id`s

2024-05-21 08:32 UTC, yevheniisynytsia requested changes
Well done! Left some minor comments

2024-05-21 08:32 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +    List<Book> findAllById(Long categoryId);
findAllById(id) in book repository sounds like we are looking for all books by **book** id. Please return categoryId back

There are two options:
1. Use ugly naming
2. Use nice naming but write a customer query

2024-05-21 08:32 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/model/Category.java
> +    }
replace with `@NoArgsConstruuctor`

2024-05-21 08:32 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/dto/BookDtoWithoutCategoryIds.java
> +
please remove empty lines

2024-05-21 08:32 UTC, yevheniisynytsia commented on src/main/java/com/example/onlinebookstore/dto/BookDtoWithoutCategoryIds.java
> +
if there are a lot of annotations - it is ok to add empty lines, but when there are no annotations above the fields, I don't see a reason to have so much empty space

2024-05-21 09:45 UTC, merged