Feature/docker
bodya4243/online-book-store pull request #14
Opened 2024-05-27 12:20 UTC by bodya4243

2024-05-27 13:33 UTC, VolandevlodD requested changes
LGTM, but please only show the changes related to Docker in this pull request. This pull request contains changes that are not related to this task!

2024-05-28 10:07 UTC, yevheniisynytsia requested changes

2024-05-28 10:07 UTC, yevheniisynytsia commented on Dockerfile
> +EXPOSE 8080
please add empty line

2024-05-28 10:07 UTC, yevheniisynytsia commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
please add empty line

2024-05-28 10:27 UTC, yevheniisynytsia requested changes
please update the branch to have files only related to docker task

2024-05-28 10:31 UTC, bodya4243 commented
So I should change comits into order. But now it's into master and the master is already merged from the order.

2024-05-28 13:09 UTC, andrii-hoienko approved these changes
Good job!

2024-05-28 14:08 UTC, merged