online-book-store/dto-web
bodya4243/online-book-store pull request #4
Opened 2024-04-24 20:23 UTC by bodya4243

1) create Dto
2) create controller
3) create mapper
4) create mapper config
5) create exception

2024-04-25 13:01 UTC, slizko1 reviewed
Gj! But some fixes are needed

2024-04-25 13:01 UTC, slizko1 commented on src/main/java/com/example/onlinebookstore/dto/BookDto.java
> +    private BigDecimal price;
Why do we need hibernate annotations for dto class? Do we need tosave them in the database?

2024-04-25 13:01 UTC, slizko1 commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +}
Same here

2024-04-25 13:01 UTC, slizko1 commented on src/main/java/com/example/onlinebookstore/service/BookServiceImpl.java
> +        book.setIsbn("isbn");
Post request will look like this фacording to the assignment guideline`{
  "title": "Sample Book 3",
  "author": "Author C",
  "isbn": "9781122334455",
  "price": 29.99,
  "description": "Yet another sample book description.",
  "coverImage": "http://example.com/cover3.jpg"
}
` So you don't neen to set this fields

2024-04-25 13:01 UTC, slizko1 commented on pom.xml
> +</project>
Add empty line

2024-04-25 13:54 UTC, andrii-hoienko requested changes
Please read students comments

2024-04-25 13:54 UTC, andrii-hoienko commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
```suggestion
		<relativePath/>
```

2024-04-25 13:54 UTC, andrii-hoienko commented on pom.xml
> +</project>
Not fixed

2024-04-25 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/dto/BookDto.java
> +    private BigDecimal price;
Agree

2024-04-25 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/dto/CreateBookRequestDto.java
> +}
Agree

2024-04-25 13:54 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/BookServiceImpl.java
> +        book.setIsbn("isbn");
agree

2024-04-26 13:13 UTC, andrii-hoienko approved these changes
Good job!

2024-04-26 13:27 UTC, merged