Feature/globalExceptionHandler
bodya4243/online-book-store pull request #6
Opened 2024-05-01 20:46 UTC by bodya4243

2024-05-02 08:16 UTC, ValentynSharshon requested changes
Good job, but some changes are needed.

2024-05-02 08:16 UTC, ValentynSharshon commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    }
I think you need to add response status to this method.

2024-05-02 08:16 UTC, ValentynSharshon commented on src/main/java/com/example/onlinebookstore/dto/BookRequestDto.java
>      private String title;
What if we get an empty string from the user as the value of the title field?

2024-05-02 08:16 UTC, ValentynSharshon commented on src/main/java/com/example/onlinebookstore/dto/BookRequestDto.java
>      private String author;
What if we get an empty string from the user as the value of the author field?

2024-05-02 08:16 UTC, ValentynSharshon commented on src/main/java/com/example/onlinebookstore/dto/BookRequestDto.java
>      private String isbn;
The ISBN value is unified and consists of 13 digits. I think it will be good to add a check for this.

2024-05-02 08:16 UTC, ValentynSharshon commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +public interface BookRepository extends JpaRepository<Book, Long> {
I don't fully understand why you need a declaration of the save, findAll and findById methods if JPA already provides an implementation of them? You can just use them in the controller.

2024-05-02 12:33 UTC, bodya4243 commented on src/main/java/com/example/onlinebookstore/dto/BookRequestDto.java
>      private String title;
we will rcieve 
{
    "timestamp": "2024-05-02T15:32:17.5297866",
    "status": "BAD_REQUEST",
    "errors": [
        "title не должно равняться null",
    ]
}

2024-05-02 15:00 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-02 15:00 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    }
Please add handling of other exception that should occur in code

2024-05-02 15:00 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/dto/BookRequestDto.java
> +    @Pattern(regexp = "\\d{13}", message = "ISBN must be a 13-digit number")
```suggestion
    @ISBN
```

2024-05-03 13:38 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-03 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    private String getErrorMessage(ObjectError e) {
Private methods should be the last in order

2024-05-03 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("errors", errors);
Code duplication

2024-05-03 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
Please make repeatable strings constants

2024-05-03 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler({EntityNotFoundException.class})
```suggestion
    @ExceptionHandler(EntityNotFoundException.class)
```

2024-05-03 13:38 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler({EntityNotFoundException.class})
Only 1 exception is thrown in code, also add handler which will handle Exception

2024-05-03 13:41 UTC, bodya4243 commented
oops havent checked all the comments one second

2024-05-03 15:01 UTC, andrii-hoienko requested changes

2024-05-03 15:01 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    private void buildErrorBody(HttpStatus status,
Discussed on QnA

2024-05-06 13:19 UTC, andrii-hoienko approved these changes
Good job!

2024-05-06 17:01 UTC, merged