Feature/pagination sorting swagger
bodya4243/online-book-store pull request #7
Opened 2024-05-02 17:18 UTC by bodya4243

2024-05-03 13:09 UTC, nklimovych requested changes
Looks good. Left you some minor comments)

2024-05-03 13:09 UTC, nklimovych commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    @Operation(summary = "get all Book", description = "get all the books")
```suggestion
    @Operation(summary = "Get all Books", description = "Get all the books")
```
Same issue in other `@Operation's`

2024-05-03 13:09 UTC, nklimovych commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
>      }
I suggest adding `@ResponseStatus` to all methods for consistency.

2024-05-03 13:09 UTC, nklimovych commented on src/main/java/com/example/onlinebookstore/dto/BookRequestDto.java
> +    @Pattern(regexp = "\\d{13}", message = "ISBN must be a 13-digit number")
There's annotation `@ISBN`, so you can use it with `@NotNull` to validate ISBN.
Just a suggestion 🙂

2024-05-06 13:22 UTC, andrii-hoienko requested changes
Please make only necessary changes in PR

2024-05-06 13:22 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/controller/BookController.java
> +    public BookDto update(@PathVariable Long id,
Is it possible to add documentation here as well

2024-05-06 13:22 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +public class CustomGlobalExceptionHandler extends ResponseEntityExceptionHandler {
These changes not related to this PR

2024-05-07 13:43 UTC, andrii-hoienko approved these changes
Good job!

2024-05-07 14:02 UTC, merged